# vim: set expandtab shiftwidth=2 tabstop=8 textwidth=0:

include:
  - project: 'wayland/ci-templates'
    ref: 955e61e67cf29327cf907432f668df9eec4ca6a2 # see https://docs.gitlab.com/ee/ci/yaml/#includefile
    file: '/templates/fedora.yml'


variables:
  FEDORA_RPMS: 'git autoconf automake libtool make xorg-x11-server-devel libudev-devel libevdev-devel libinput-devel xorg-x11-util-macros'
  FEDORA_TAG: '2020-05-19.0'
  UPSTREAM_REPO: xorg/drivers/xf86-input-libinput
  BUILDAH_IMAGE: $CI_REGISTRY/wayland/ci-templates/buildah:latest
  FEDORA_CONTAINER_IMAGE: $CI_REGISTRY_IMAGE/fedora/$FEDORA_VERSION:$FEDORA_TAG


stages:
  - containers-build
  - build


container_build:
  extends: .fedora@container-ifnot-exists
  stage: containers-build
  variables:
    GIT_STRATEGY: none
    FEDORA_VERSION: 32


.default_artifacts: &default_artifacts
  artifacts:
    name: "automake-logs-$CI_JOB_NAME"
    when: always
    expire_in: 1 week
    paths:
      - _builddir/config.log


.default_build: &default_build
  script:
    - mkdir _builddir _inst
    - pushd _builddir > /dev/null
    - ../autogen.sh --prefix=$(realpath ../_inst) --disable-silent-rules
    - make && make check
    - make install
    - popd > /dev/null


.build@template:
  stage: build
  <<: *default_artifacts
  <<: *default_build
  dependencies: []


.fedora-build@template:
  extends: .build@template
  image: $FEDORA_CONTAINER_IMAGE


fedora:32@default-build:
  extends: .fedora-build@template
  variables:
    FEDORA_VERSION: 32
